package assignment89;
import java.util.ArrayList;
import java.util.Collection;
public class Collectionsprogram {
	public static void main(String[]args)
	{
		Collection<Integer> c1=new ArrayList<Integer>();
		c1.add(89);
		c1.add(90);
		c1.add(77);
		System.out.println(c1);
		System.out.println("Before removing->"+c1);
		c1.remove(90);
		System.out.println("After removing->"+c1);
		c1.addAll(c1);
		System.out.println("Before removing->"+c1);
		c1.removeAll(c1);
		System.out.println("After removing->"+c1);
		boolean b1=c1.contains(70);
		System.out.println(b1);
		boolean b2=c1.containsAll(c1);
		System.out.println(b2);
Collection<Double> c2=new ArrayList<Double>();
		c2.add(89.67);
		c2.add(90.98);
		c2.add(77.76);
		System.out.println(c2);
		System.out.println("Before removing->"+c2);
		c2.remove(90.98);
		System.out.println("After removing->"+c2);
		c2.addAll(c2);
		System.out.println("Before removing->"+c2);
		c2.removeAll(c2);
		System.out.println("After removing->"+c2);
		boolean b3=c2.contains(70.00);
		System.out.println(b1);
		boolean b4=c2.containsAll(c1);
		System.out.println(b2);
Collection<Character> c3=new ArrayList<Character>();
		c3.add('A');
		c3.add('B');
		c3.add('C');
		System.out.println(c3);
		System.out.println("Before removing->"+c3);
		c3.remove('B');
		System.out.println("After removing->"+c3);
		c3.addAll(c3);
		System.out.println("Before removing->"+c3);
		c3.removeAll(c3);
		System.out.println("After removing->"+c3);
		boolean b5=c3.contains('E');
		System.out.println(b5);
		boolean b6=c3.containsAll(c1);
		System.out.println(b6);
Collection<String> c4=new ArrayList<String>();
		c4.add("Riya");
		c4.add("Manu");
		c4.add("Rashmi");
		System.out.println(c4);
		System.out.println("Before removing->"+c4);
		c4.remove("Rashmi");
		System.out.println("After removing->"+c4);
		c4.addAll(c4);
		System.out.println("Before removing->"+c4);
		c4.removeAll(c4);
		System.out.println("After removing->"+c4);
		boolean b7=c4.contains("Ramya");
		System.out.println(b7);
		boolean b8=c4.containsAll(c1);
		System.out.println(b8);
		}
}
